#cloud-config
users:
  - default
  - name: ajdj
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_import_id: 
      - gh:ajdj

  # Ansible user
  - name: ansible
    gecos: Ansible User
    shell: /bin/bash
    groups: users,admin,wheel,lxd
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_import_id: 

# Packages and updates
package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip
  - wireguard
  - wireguard-tools
  - ufw

# Install Ansible & WG playbook
ansible:
  install_method: pip
  pull:
    url: "https://github.com/arjf/wg-iac.git"
    playbook_name: "ansible/wireguard.yml"