#cloud-config
users:
  - default
  - name: ajdj
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_import_id: 
      - gh:ajdj

# Packages and updates
package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip
  - wireguard
  - wireguard-tools
  - ufw

# Install Ansible & WG playbook
ansible:
  install_method: pip
  pull:
    - url