core:
    admin_user: ENC[AES256_GCM,data:uaZ0hzxRSfZjubkm9T68k07Sug==,iv:V4QcbM2NYn2eBp7DksCjsEbLb4Iv4xqVXpjYquOjuPY=,tag:uDizSx/t+rs8bBWunnLk8w==,type:str]
    admin_password: ENC[AES256_GCM,data:Awpx2WY2,iv:3EHXhz5hJWriqcLBre8y5J1VUEzk9UlFAEfPMI164Ww=,tag:o7Zsqy7z4Oy3dLhVlytDvw==,type:str]
    admin_api_token: ENC[AES256_GCM,data:Fj34yobrswvA8LuzrTGvlUzKZmzEXvJVHs9SJOxY5/4aaOKZ,iv:5FfpNwC4sIH1hhdCLSD+ZPcBOlElnGfOPc1w3FCtEM0=,tag:3hfhq4uoSklKZFI+6McZGQ==,type:str]
    import_existing: ENC[AES256_GCM,data:Bj8ONQ==,iv:Ckm6gqHoAU9gpucTv6a7BhOjN5eNE3hcMNnbhrmsC1c=,tag:FK3zHSA7T1FaC+rqlRyBLQ==,type:bool]
    create_default_peer: ENC[AES256_GCM,data:g15CnQ==,iv:pVAcwW7McQnX9grLEWYfYl38u35RAc2AZ8M3opAM7GE=,tag:6JfnUyIz6Kyr1WCTlqtrOA==,type:bool]
    self_provisioning_allowed: ENC[AES256_GCM,data:FBgJQg==,iv:ZAizzWtCbm1CPfPLwLdwvXN3D+sw9rbC+3u9ACbqcl4=,tag:NhnO1fvhLGxvlLvipEACiw==,type:bool]
backend:
    default: ENC[AES256_GCM,data:s6C64hY=,iv:BFQpwq49ixlkmN0VuSdu9bYUWjdT8F0kvkZsXW2yV6M=,tag:fCXfwKePlZ1tTnJhMIdFXA==,type:str]
web:
    site_title: ENC[AES256_GCM,data:UX1zcBz9q7OQ1pw=,iv:emV/RBp2zOsdfgs8lNG/XOSeBbLzlNOCcGfcXOVyTQI=,tag:76C+s9FUDEA+t6EXpRPYoA==,type:str]
    site_company_name: ENC[AES256_GCM,data:DN95xg==,iv:ZE1MnF0TIH4TByUGQVnRpPKn2oSsudy8LycDNsrawj0=,tag:UXNsf99omZKz+VZdrAa6tg==,type:str]
    listening_address: ENC[AES256_GCM,data:B/pH8TA=,iv:buxuPXEJ3UpnwhH56kB2JZIhlgteqcrHYteRVdz3wAo=,tag:iX3fNQ6am8ujaQsj3pdUCw==,type:str]
    external_url: ENC[AES256_GCM,data:KtDkiDnhEXMCT0GH681LOq5Ohw==,iv:RfdxyqO0GUkoflShXDh3QVinc9DO+NlhHPRhNhnOERQ=,tag:KregS+37ViDeE4fYD4Vi+A==,type:str]
    csrf_secret: ENC[AES256_GCM,data:xxaIjx8b1Km7q605hiy41W4f5qhvndCXWdrbLeh98OTKosThS0OeBC27ySlOE2OJuQrPTjf3brPP6AxSjzAfSw==,iv:Sh9ea9Hh94uu8sHZmaJ8MV/DalFK2HSieayvQqEHkjY=,tag:vSzjRf05a3A0aj/PY8rcKw==,type:str]
    session_secret: ENC[AES256_GCM,data:0iZC6Emoex59ha+z59PNwdjig4q0rHu9RowWZMm69wwiP1W47ZjF+zvYF1JHVCXI1AEjuVmQuAc7IT5aE90+2A==,iv:I7qzn3SjaJD3EuLjmzrx+f5S1SoQAhOnvEK8He/sdJU=,tag:5QSYGUaLsIIdAlwIYNXKmw==,type:str]
    request_logging: ENC[AES256_GCM,data:5xzkgw==,iv:J1KKA9SvcuUCUaix6p/axbRzjEPTb1r+MegTWmwMbeU=,tag:mn2oO8PTRkAuX2U78OlnQg==,type:bool]
advanced:
    log_level: ENC[AES256_GCM,data:RGptDjU=,iv:fdfgBtriYSprifbJus/Bz7tfcOtZ1jmn0ZB7DNXM11E=,tag:ovkSwAy4YwZZMDr3kd7t2A==,type:str]
    start_listen_port: ENC[AES256_GCM,data:B9hkMqY=,iv:1h0RxtfWsHdeX/7QcVzdP7I7qJ51SSyL7M/Doz4llMA=,tag:rVCv2zQwRrypGULC7UgZgw==,type:int]
    start_cidr_v4: ENC[AES256_GCM,data:aHtS4JxLrVRawDk=,iv:fQ1kjXqbqEzlPzOobYwRuXJS/7b5vg6DNkAoZjvwXFs=,tag:0UqipWjNxVdzITK1LDQkwQ==,type:str]
    use_ip_v6: ENC[AES256_GCM,data:KvGwUw==,iv:XBMEPZsmtj+p2KzANrMpSvovcLhLUUQ+jNAK+UgPIQs=,tag:i7+n25A7MYr9isNrf1jZ6w==,type:bool]
    log_pretty: ENC[AES256_GCM,data:oIrrNA==,iv:eTkWQKnrEVGrZxtDywO14Uoxf3w0RLVXmYf5p6W2gX4=,tag:iwmH9KHuT9uyTf0KiJlm4g==,type:bool]
    log_json: ENC[AES256_GCM,data:9QtdNTo=,iv:sWTwP3E9GvTFvqHeF16NFYsDct+GEB35HqK8ADqKJDk=,tag:UxRota8b8k/f5lZ/+SAEYQ==,type:bool]
    config_storage_path: ENC[AES256_GCM,data:oSrFXLkNlgX730sMqP8=,iv:jVfpqunwBMcT7cx9r/4EJ3KHVy4eCpP/2GJ3y9+xiG0=,tag:LamNbSag0Hb8WfWzcFdTww==,type:str]
    expiry_check_interval: ENC[AES256_GCM,data:H4U=,iv:/+8zoqTBjluKjTxVn214UW5e1suXM5TISHf5BDuSA00=,tag:e0+EnUfDqOi+/vJVQ/TJbg==,type:str]
database:
    debug: ENC[AES256_GCM,data:O6zosQ==,iv:cXJ4fmYZpm8sn02uhtbzaYwnuATxTVDf0Ds3u5RBEjY=,tag:aO0ZTH2BUHGsNtmw0R9UtA==,type:bool]
    type: ENC[AES256_GCM,data:FPWglUaD,iv:pIi03fPv8x+pRIqyiIAkEX+WsQxUN+FGc48bWZusfVc=,tag:/sQ9+oQgliwPqWqzlt9FOg==,type:str]
    dsn: ENC[AES256_GCM,data:kbvLGSrepbRZ7va+wWU=,iv:nBdC5lwvFzlgUyTa0OSVsxDuqeR5dX6QJCMmlEuydzk=,tag:jlbTmga12+rdTzXKDikBoQ==,type:str]
    encryption_passphrase: ENC[AES256_GCM,data:wF2FYLjP8vzp7MbjRDyX/e/JepuSFDOUg8zgyWbaJTZlOfLcIeINkf6G41A=,iv:eY2vlKJuk+sVyzCggsuWpfrDoxNfa9mqRvTyvAb5QDI=,tag:1sKzdJIcGyXVuHTd1SJ1/A==,type:str]
statistics:
    use_ping_checks: ENC[AES256_GCM,data:A0wOmw==,iv:LH3HGHD8/BrsDqL94ylZYa7QHB1bSHo/nM38fYY4eM8=,tag:tp9QWjh9IGSIZ6R/JG6tJg==,type:bool]
    ping_check_workers: ENC[AES256_GCM,data:jg==,iv:yJBtw21zM4YJm1kqh0duxoYFPPaasLzjTNdQB77GOYQ=,tag:y3jNVm9C3naWy3KWZPGiXQ==,type:int]
    ping_unprivileged: ENC[AES256_GCM,data:hJap7w==,iv:veLV74ZP+8oGRMYYXrqesFzqS6MTjj7zIEtFjDS72Io=,tag:zMOH89PgKVtzHAXZUmhCvg==,type:bool]
    ping_check_interval: ENC[AES256_GCM,data:hTc=,iv:NkV1J3Bb140C5b+A4a7XTNYj3V9iBbH66aenZl5B5Ko=,tag:VqoEGyuTyDXbcTqfkpwMDA==,type:str]
    data_collection_interval: ENC[AES256_GCM,data:gm0x,iv:ZHk5WgIL9mkTHOIq8lpTvcJ5LIDzYTEDKoni4rARDxU=,tag:+8Lzt6QLRYmn8KzKR8XE/g==,type:str]
    collect_interface_data: ENC[AES256_GCM,data:5nJLSw==,iv:uWfWPW2frCycdYu7wBtj6aDK5R0anY1hYEkW5Hr7Gio=,tag:dztKtS05862qWMGFbzys3A==,type:bool]
    collect_peer_data: ENC[AES256_GCM,data:HZw+4w==,iv:CmXoz61PpJ/JUCQxUxMHiea436gRX45J840XdNe9bsY=,tag:3BYT4rr8ogNZ7jGaRXkUzw==,type:bool]
    collect_audit_data: ENC[AES256_GCM,data:754VMw==,iv:Wc7J+Lr7QVFHmO61so1J0u4hlfs7WiekMom8qFiA0F4=,tag:Ze8oPYFfaJWTiqV4O8/sMg==,type:bool]
    listening_address: ENC[AES256_GCM,data:r9Cveso=,iv:Djlz7pOKIkTENi5aqPRdTl1FkRE8UmrUQgUwwowD5Tg=,tag:j+AhR0nQhVAf4gPq08mZvg==,type:str]
auth:
    webauthn:
        enabled: ENC[AES256_GCM,data:n1IOPA==,iv:/PCYOCvliwNbsak77b1syCF1O5WpfrwmrdfM8q9liDk=,tag:MW3DDCVElvlcppRlaBA/MQ==,type:bool]
sops:
    lastmodified: "2025-10-01T15:37:49Z"
    mac: ENC[AES256_GCM,data:R6StAV+/Taf76ue00Koup1V5H+vMAtYpZA1pY+yyijgppoJbCRDCKCFPHL6h0yiODoZ5V4r9FUTvUQ9U3TlB4uHsr1lpzz5EWjjrIGr/Ez92IbT16IQbIV6EuVg61zhXQwqEISFR1BnwIzSj1l1X3mOt8dFXxvC9tbg/DIWYqwo=,iv:pGPX0DFsUA+a0sqhhw1HqO3g3rh5PI7F1TQUf8p10Xs=,tag:fDBjyLy6EK9f5pd1LDVG3g==,type:str]
    pgp:
        - created_at: "2025-10-01T15:37:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA/3afRQ0TPQqAQf7BxZTaGMz7539c+kQiSiNQ5x6BRbGnBN+Ae1c6sb/8Dwn
            IKxn77fDctDcwupR9Gh3ykD6u78hnrbKu/ySOX8qQoQ+FBNdk/Q2zPG4dQfSJpeK
            jMCJ4sjBqZxi+CrCzh4gTluNYfKzBACLsYgpzZTgGgkcdHphyzHYymJCt21LGLX7
            yH1U2pcuIiV3/y3eI9ecRRA1SBLtFy0Kei6BD2XhLfjkhE0ozTHXTaxKaqY2ekUH
            /lg2cVX7NlLdG1SHiP4RtU4rQoSdy0bg7eX3cBYrKxworaFKaz9JR20OmBIoRhZ+
            5euJuu5ioLVq0BMrFd7Wqy0wnx/kRA6lJAOLS0ndt9JcAWux3M3Hr21RkXXsvPSq
            lnAoO2lGGF3xpT0V+e+BKaaNyJGaaHiv/tk0mmf19KKFSk+zwWgUxLEEOu3z6tdT
            5tAVatUFcOQCnJjiQIfYz4PdF4U9U5yw91Jo3EM=
            =4kOr
            -----END PGP MESSAGE-----
          fp: C8269280C7A7B91A0A310682DE6ADEF249378D12
        - created_at: "2025-10-01T15:37:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw7ktSov7Xc0AQ/7BXyJvkEIZhjcyHiigz/q7Mg2Clg+qI9GkaGPMql9XLC1
            25Ekdmf34i+5CdbscowMyhsIgAPXQVq/DVnP7PlPfLZ8N1RTRtFPwppHFbBdJlMw
            JGxi55GC/cAB0Fuj2zwZeHmGJjxm5/37bm9hebg6zDBJ+wEU782aVMOhZr9WVRlK
            kBv39/61qesyiWCEvFNUiHH/T3DeSPehbwwmxlQGZBBmYsYZNUHk9TVBN6Ojgx80
            7oWM1xJanZk70bBvkb7260o1Bq4Sl1l+u7THErRSWLFxWdQwoD43i6v06k8RLlro
            iYHtu0XAzPXVsVjZIOWXEzXZvmLdftl9e8mt8XU2LOUVY5gdTyqtcfzR0fvEJAat
            tqEEaTlisJClrJuuStgwYP5soa9jwhVgcZbCa4G3zr9lkeOnfVjvFyCxI4vXCPF1
            US+2eDLT+Eax0Aiz9eeQT3xPl41NMmLCE/Bodef4OuZ+gMeVf5rUUg0ceszWaoF6
            wQS5qhi3cYWhSEl7+zvWc6FRCd4RcF/xtVPVj5FH9W/xDENvqX6bIKBWoMWGmYVh
            J6BEo54N2BzuUa2AI8Mg/UAtBxJo79XF3UHDtRE8BtUOLY7ckVTRq2vPGlaL0emQ
            7YOJjkzu7SBhuGdF8oQsZbG9tcBXmwlBtd8PQV3rcnCPBB0DU5vAX5beI2J2P//S
            XAEyvzkIduKNLpij5R2WuDVSmbiNEfTYXU+48/2l4fD4mO03Dvvzwpou1qnHlVJT
            X3GVNbHzxTtR+rsderAEQoT8D9nyv17GXQVbkOlqUgFUr5BypQ/cQidnhsy7
            =gTAz
            -----END PGP MESSAGE-----
          fp: 24650170F1319CE57856B4D0A2053B74E1C7FC25
    unencrypted_suffix: _unencrypted
    version: 3.11.0
