---
- name: Setup wireguard in a lxc
  hosts: wg-container
  remote_user: ansible

  tasks:
    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true
        sysctl_set: true

    - name: Enable IPv6 forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present
        reload: true
        sysctl_set: true

    - name: Ensure UFW default policies are set
      community.general.ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    - name: Setup UFW rules for WireGuard
      community.general.ufw:
        rule: allow
        port: "51820"
        proto: udp
        src: any

    - name: SSH over v4
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp
        src: "0.0.0.0/0"

    - name: WG-portal over v4
      community.general.ufw:
        rule: allow
        port: "8080"
        proto: tcp
        src: "0.0.0.0/0"

    - name: Enable UFW
      community.general.ufw:
        state: enabled
    - name: Reload UFW
      community.general.ufw:
        state: reloaded

    - name: Create wg-portal dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - /opt/wg-portal
        - /var/lib/wg-portal/data
        - /etc/wireguard
        - /opt/wg-portal/config

    - name: Get wg-portal binary
      ansible.builtin.get_url:
        url: "https://github.com/h44z/wg-portal/releases/latest/download/wg-portal_linux_amd64"
        dest: /opt/wg-portal/wg-portal
        mode: '0755'
        owner: root
        group: root

    - name: Copy wg-portal config
      ansible.builtin.copy:
        src: "../wg-app/config.yaml"
        dest: /opt/wg-portal/config/config.yaml
        owner: root
        mode: '0600'

    - name: Install systemd service
      ansible.builtin.copy:
        src: "../wg-app/wg-portal.service"
        dest: /etc/systemd/system/wg-portal.service
        mode: '0644'
        owner: root
      notify:
        - reload systemd
        - start wg-portal

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start wg-portal
      ansible.builtin.systemd:
        name: wg-portal
        state: started
        enabled: true
